language: java
sudo: false
install: true

jdk:
  - openjdk8
  - openjdk11
  - openjdk12
  #  - openjdk13
  - openjdk-ea
  #  - oraclejdk8
  - oraclejdk11

matrix:
  allow_failures:
    - jdk: openjdk-ea

env:
  - AWS_TEST_BUCKET=s3-tests.s3-eu-west-1.amazonaws.com
  - AWS_TEST_BUCKET=s3.eu-central-1.amazonaws.com/s3-tests-2
  - AWS_TEST_BUCKET=s3.amazonaws.com/s3-tests-3

after_success:
  - mvn -V -B -e jacoco:report
  - bash <(curl -s https://codecov.io/bash)
