language: java
sudo: false
install: true
script:
  - cd commons-vfs && mvn install && cd .. && mvn cobertura:cobertura verify

jdk:
  - openjdk8
  - oraclejdk8

env:
  global:
  - AWS_TEST_BUCKET=s3-tests

after_success:
  - bash <(curl -s https://codecov.io/bash)
  