language: java
sudo: false
install: true
script:
  - cd commons-vfs && mvn -B install -DskipTests && cd .. && mvn -B cobertura:cobertura verify

jdk:
  - openjdk8
  - oraclejdk8
  - oraclejdk11

env:
  global:
  - AWS_TEST_BUCKET=s3-tests.s3-eu-west-1.amazonaws.com

after_success:
  - bash <(curl -s https://codecov.io/bash)
  