language: java
sudo: false
install: true

matrix:
  include:
    - jdk: openjdk8
      env:
        - BASE_URL=s3://s3-tests.s3-eu-west-1.amazonaws.com
        - secure: "UAZpxNjODj8kfIr70zWwVSRZtMKD/bXql8kLq5HQ+i5i+5COIzEBrs+4snj5ENmg6TuNNhOWI8JdtlvHMyRvt/es0rdsygjk9YHfVR3FEWua9VVfsFMKTVVjCf/gH2V+7jqVlNP1uSMp2TfH7LUpfeWXkutO31VnxRX1ZIDhRaI="
        - secure: "PNJ2NZioKdt5jyBMDpKxtPCUY2MV+dou/V8JRyuoeh0vlBZ5ujrFSbwNOb4xyEjFGBLK/bqIL2jm6vBEbNnvL2TTk20ybVKQDl+QivMjSHajwcbr8mtmwpe3HVC+QC68PXS1wITOWO8GZnvkLn8SQoLSSEoR4Maj9z2HY+W7ZBs="
    - jdk: openjdk8
      env:
        - BASE_URL=s3://s3.eu-central-1.amazonaws.com/s3-tests-2
        - secure: "UAZpxNjODj8kfIr70zWwVSRZtMKD/bXql8kLq5HQ+i5i+5COIzEBrs+4snj5ENmg6TuNNhOWI8JdtlvHMyRvt/es0rdsygjk9YHfVR3FEWua9VVfsFMKTVVjCf/gH2V+7jqVlNP1uSMp2TfH7LUpfeWXkutO31VnxRX1ZIDhRaI="
        - secure: "PNJ2NZioKdt5jyBMDpKxtPCUY2MV+dou/V8JRyuoeh0vlBZ5ujrFSbwNOb4xyEjFGBLK/bqIL2jm6vBEbNnvL2TTk20ybVKQDl+QivMjSHajwcbr8mtmwpe3HVC+QC68PXS1wITOWO8GZnvkLn8SQoLSSEoR4Maj9z2HY+W7ZBs="
    - jdk: openjdk8
      env:
        - BASE_URL=s3://s3.amazonaws.com/s3-tests-3
        - secure: "UAZpxNjODj8kfIr70zWwVSRZtMKD/bXql8kLq5HQ+i5i+5COIzEBrs+4snj5ENmg6TuNNhOWI8JdtlvHMyRvt/es0rdsygjk9YHfVR3FEWua9VVfsFMKTVVjCf/gH2V+7jqVlNP1uSMp2TfH7LUpfeWXkutO31VnxRX1ZIDhRaI="
        - secure: "PNJ2NZioKdt5jyBMDpKxtPCUY2MV+dou/V8JRyuoeh0vlBZ5ujrFSbwNOb4xyEjFGBLK/bqIL2jm6vBEbNnvL2TTk20ybVKQDl+QivMjSHajwcbr8mtmwpe3HVC+QC68PXS1wITOWO8GZnvkLn8SQoLSSEoR4Maj9z2HY+W7ZBs="
    - jdk: openjdk8
      env:
        - BASE_URL=s3://storage.yandexcloud.net/s3-tests
        - secure: "H35SN7WfvG52NIOmE7QzzWkSxGPSXijftejiUt1OwHMbr9jtp9NWk8SxFNabaKXpOW9xg9PnzyDOiORFxKWtqzzdrqcVZTHrXN652b0EA3YXr1QFM0HLGy1paiMVksYPDO73PVWeQvDaxthHzB+Ysff+QhN67vC7sbsRCOG7KXo="
        - secure: "jSJS2PbNVozYnWl4b7/1WOCby8JtvyuM3FE8ulF4jrxEFKAxn3hlSo+EgehZnk5C4/gMBuEljSE+W95NQzgKhEDk1gpHfCqYGjRjwCxsEXK+qRBUSopI0GFsQVAtSZc3nky+NNqDRs8UBMP+rNxAfysw5b+4hKK8M3fw3oTdwrg="
    - jdk: openjdk8
      env:
        - BASE_URL=s3://s3-tests.storage.yandexcloud.net/
        - secure: "H35SN7WfvG52NIOmE7QzzWkSxGPSXijftejiUt1OwHMbr9jtp9NWk8SxFNabaKXpOW9xg9PnzyDOiORFxKWtqzzdrqcVZTHrXN652b0EA3YXr1QFM0HLGy1paiMVksYPDO73PVWeQvDaxthHzB+Ysff+QhN67vC7sbsRCOG7KXo="
        - secure: "jSJS2PbNVozYnWl4b7/1WOCby8JtvyuM3FE8ulF4jrxEFKAxn3hlSo+EgehZnk5C4/gMBuEljSE+W95NQzgKhEDk1gpHfCqYGjRjwCxsEXK+qRBUSopI0GFsQVAtSZc3nky+NNqDRs8UBMP+rNxAfysw5b+4hKK8M3fw3oTdwrg="

    - jdk: openjdk11
      env:
        - BASE_URL=s3://s3-tests.s3-eu-west-1.amazonaws.com
        - secure: "UAZpxNjODj8kfIr70zWwVSRZtMKD/bXql8kLq5HQ+i5i+5COIzEBrs+4snj5ENmg6TuNNhOWI8JdtlvHMyRvt/es0rdsygjk9YHfVR3FEWua9VVfsFMKTVVjCf/gH2V+7jqVlNP1uSMp2TfH7LUpfeWXkutO31VnxRX1ZIDhRaI="
        - secure: "PNJ2NZioKdt5jyBMDpKxtPCUY2MV+dou/V8JRyuoeh0vlBZ5ujrFSbwNOb4xyEjFGBLK/bqIL2jm6vBEbNnvL2TTk20ybVKQDl+QivMjSHajwcbr8mtmwpe3HVC+QC68PXS1wITOWO8GZnvkLn8SQoLSSEoR4Maj9z2HY+W7ZBs="
    - jdk: openjdk11
      env:
        - BASE_URL=s3://s3.eu-central-1.amazonaws.com/s3-tests-2
        - secure: "UAZpxNjODj8kfIr70zWwVSRZtMKD/bXql8kLq5HQ+i5i+5COIzEBrs+4snj5ENmg6TuNNhOWI8JdtlvHMyRvt/es0rdsygjk9YHfVR3FEWua9VVfsFMKTVVjCf/gH2V+7jqVlNP1uSMp2TfH7LUpfeWXkutO31VnxRX1ZIDhRaI="
        - secure: "PNJ2NZioKdt5jyBMDpKxtPCUY2MV+dou/V8JRyuoeh0vlBZ5ujrFSbwNOb4xyEjFGBLK/bqIL2jm6vBEbNnvL2TTk20ybVKQDl+QivMjSHajwcbr8mtmwpe3HVC+QC68PXS1wITOWO8GZnvkLn8SQoLSSEoR4Maj9z2HY+W7ZBs="
    - jdk: openjdk11
      env:
        - BASE_URL=s3://s3.amazonaws.com/s3-tests-3
        - secure: "UAZpxNjODj8kfIr70zWwVSRZtMKD/bXql8kLq5HQ+i5i+5COIzEBrs+4snj5ENmg6TuNNhOWI8JdtlvHMyRvt/es0rdsygjk9YHfVR3FEWua9VVfsFMKTVVjCf/gH2V+7jqVlNP1uSMp2TfH7LUpfeWXkutO31VnxRX1ZIDhRaI="
        - secure: "PNJ2NZioKdt5jyBMDpKxtPCUY2MV+dou/V8JRyuoeh0vlBZ5ujrFSbwNOb4xyEjFGBLK/bqIL2jm6vBEbNnvL2TTk20ybVKQDl+QivMjSHajwcbr8mtmwpe3HVC+QC68PXS1wITOWO8GZnvkLn8SQoLSSEoR4Maj9z2HY+W7ZBs="
    - jdk: openjdk11
      env:
        - BASE_URL=s3://storage.yandexcloud.net/s3-tests
        - secure: "H35SN7WfvG52NIOmE7QzzWkSxGPSXijftejiUt1OwHMbr9jtp9NWk8SxFNabaKXpOW9xg9PnzyDOiORFxKWtqzzdrqcVZTHrXN652b0EA3YXr1QFM0HLGy1paiMVksYPDO73PVWeQvDaxthHzB+Ysff+QhN67vC7sbsRCOG7KXo="
        - secure: "jSJS2PbNVozYnWl4b7/1WOCby8JtvyuM3FE8ulF4jrxEFKAxn3hlSo+EgehZnk5C4/gMBuEljSE+W95NQzgKhEDk1gpHfCqYGjRjwCxsEXK+qRBUSopI0GFsQVAtSZc3nky+NNqDRs8UBMP+rNxAfysw5b+4hKK8M3fw3oTdwrg="
    - jdk: openjdk11
      env:
        - BASE_URL=s3://s3-tests.storage.yandexcloud.net/
        - secure: "H35SN7WfvG52NIOmE7QzzWkSxGPSXijftejiUt1OwHMbr9jtp9NWk8SxFNabaKXpOW9xg9PnzyDOiORFxKWtqzzdrqcVZTHrXN652b0EA3YXr1QFM0HLGy1paiMVksYPDO73PVWeQvDaxthHzB+Ysff+QhN67vC7sbsRCOG7KXo="
        - secure: "jSJS2PbNVozYnWl4b7/1WOCby8JtvyuM3FE8ulF4jrxEFKAxn3hlSo+EgehZnk5C4/gMBuEljSE+W95NQzgKhEDk1gpHfCqYGjRjwCxsEXK+qRBUSopI0GFsQVAtSZc3nky+NNqDRs8UBMP+rNxAfysw5b+4hKK8M3fw3oTdwrg="

    - jdk: openjdk12
      env:
        - BASE_URL=s3://s3-tests.s3-eu-west-1.amazonaws.com
        - secure: "UAZpxNjODj8kfIr70zWwVSRZtMKD/bXql8kLq5HQ+i5i+5COIzEBrs+4snj5ENmg6TuNNhOWI8JdtlvHMyRvt/es0rdsygjk9YHfVR3FEWua9VVfsFMKTVVjCf/gH2V+7jqVlNP1uSMp2TfH7LUpfeWXkutO31VnxRX1ZIDhRaI="
        - secure: "PNJ2NZioKdt5jyBMDpKxtPCUY2MV+dou/V8JRyuoeh0vlBZ5ujrFSbwNOb4xyEjFGBLK/bqIL2jm6vBEbNnvL2TTk20ybVKQDl+QivMjSHajwcbr8mtmwpe3HVC+QC68PXS1wITOWO8GZnvkLn8SQoLSSEoR4Maj9z2HY+W7ZBs="
    - jdk: openjdk12
      env:
        - BASE_URL=s3://s3.eu-central-1.amazonaws.com/s3-tests-2
        - secure: "UAZpxNjODj8kfIr70zWwVSRZtMKD/bXql8kLq5HQ+i5i+5COIzEBrs+4snj5ENmg6TuNNhOWI8JdtlvHMyRvt/es0rdsygjk9YHfVR3FEWua9VVfsFMKTVVjCf/gH2V+7jqVlNP1uSMp2TfH7LUpfeWXkutO31VnxRX1ZIDhRaI="
        - secure: "PNJ2NZioKdt5jyBMDpKxtPCUY2MV+dou/V8JRyuoeh0vlBZ5ujrFSbwNOb4xyEjFGBLK/bqIL2jm6vBEbNnvL2TTk20ybVKQDl+QivMjSHajwcbr8mtmwpe3HVC+QC68PXS1wITOWO8GZnvkLn8SQoLSSEoR4Maj9z2HY+W7ZBs="
    - jdk: openjdk12
      env:
        - BASE_URL=s3://s3.amazonaws.com/s3-tests-3
        - secure: "UAZpxNjODj8kfIr70zWwVSRZtMKD/bXql8kLq5HQ+i5i+5COIzEBrs+4snj5ENmg6TuNNhOWI8JdtlvHMyRvt/es0rdsygjk9YHfVR3FEWua9VVfsFMKTVVjCf/gH2V+7jqVlNP1uSMp2TfH7LUpfeWXkutO31VnxRX1ZIDhRaI="
        - secure: "PNJ2NZioKdt5jyBMDpKxtPCUY2MV+dou/V8JRyuoeh0vlBZ5ujrFSbwNOb4xyEjFGBLK/bqIL2jm6vBEbNnvL2TTk20ybVKQDl+QivMjSHajwcbr8mtmwpe3HVC+QC68PXS1wITOWO8GZnvkLn8SQoLSSEoR4Maj9z2HY+W7ZBs="
    - jdk: openjdk12
      env:
        - BASE_URL=s3://storage.yandexcloud.net/s3-tests
        - secure: "H35SN7WfvG52NIOmE7QzzWkSxGPSXijftejiUt1OwHMbr9jtp9NWk8SxFNabaKXpOW9xg9PnzyDOiORFxKWtqzzdrqcVZTHrXN652b0EA3YXr1QFM0HLGy1paiMVksYPDO73PVWeQvDaxthHzB+Ysff+QhN67vC7sbsRCOG7KXo="
        - secure: "jSJS2PbNVozYnWl4b7/1WOCby8JtvyuM3FE8ulF4jrxEFKAxn3hlSo+EgehZnk5C4/gMBuEljSE+W95NQzgKhEDk1gpHfCqYGjRjwCxsEXK+qRBUSopI0GFsQVAtSZc3nky+NNqDRs8UBMP+rNxAfysw5b+4hKK8M3fw3oTdwrg="
    - jdk: openjdk12
      env:
        - BASE_URL=s3://s3-tests.storage.yandexcloud.net/
        - secure: "H35SN7WfvG52NIOmE7QzzWkSxGPSXijftejiUt1OwHMbr9jtp9NWk8SxFNabaKXpOW9xg9PnzyDOiORFxKWtqzzdrqcVZTHrXN652b0EA3YXr1QFM0HLGy1paiMVksYPDO73PVWeQvDaxthHzB+Ysff+QhN67vC7sbsRCOG7KXo="
        - secure: "jSJS2PbNVozYnWl4b7/1WOCby8JtvyuM3FE8ulF4jrxEFKAxn3hlSo+EgehZnk5C4/gMBuEljSE+W95NQzgKhEDk1gpHfCqYGjRjwCxsEXK+qRBUSopI0GFsQVAtSZc3nky+NNqDRs8UBMP+rNxAfysw5b+4hKK8M3fw3oTdwrg="

    - jdk: openjdk-ea
      env:
        - BASE_URL=s3://s3-tests.s3-eu-west-1.amazonaws.com
        - secure: "UAZpxNjODj8kfIr70zWwVSRZtMKD/bXql8kLq5HQ+i5i+5COIzEBrs+4snj5ENmg6TuNNhOWI8JdtlvHMyRvt/es0rdsygjk9YHfVR3FEWua9VVfsFMKTVVjCf/gH2V+7jqVlNP1uSMp2TfH7LUpfeWXkutO31VnxRX1ZIDhRaI="
        - secure: "PNJ2NZioKdt5jyBMDpKxtPCUY2MV+dou/V8JRyuoeh0vlBZ5ujrFSbwNOb4xyEjFGBLK/bqIL2jm6vBEbNnvL2TTk20ybVKQDl+QivMjSHajwcbr8mtmwpe3HVC+QC68PXS1wITOWO8GZnvkLn8SQoLSSEoR4Maj9z2HY+W7ZBs="
    - jdk: openjdk-ea
      env:
        - BASE_URL=s3://s3.eu-central-1.amazonaws.com/s3-tests-2
        - secure: "UAZpxNjODj8kfIr70zWwVSRZtMKD/bXql8kLq5HQ+i5i+5COIzEBrs+4snj5ENmg6TuNNhOWI8JdtlvHMyRvt/es0rdsygjk9YHfVR3FEWua9VVfsFMKTVVjCf/gH2V+7jqVlNP1uSMp2TfH7LUpfeWXkutO31VnxRX1ZIDhRaI="
        - secure: "PNJ2NZioKdt5jyBMDpKxtPCUY2MV+dou/V8JRyuoeh0vlBZ5ujrFSbwNOb4xyEjFGBLK/bqIL2jm6vBEbNnvL2TTk20ybVKQDl+QivMjSHajwcbr8mtmwpe3HVC+QC68PXS1wITOWO8GZnvkLn8SQoLSSEoR4Maj9z2HY+W7ZBs="
    - jdk: openjdk-ea
      env:
        - BASE_URL=s3://s3.amazonaws.com/s3-tests-3
        - secure: "UAZpxNjODj8kfIr70zWwVSRZtMKD/bXql8kLq5HQ+i5i+5COIzEBrs+4snj5ENmg6TuNNhOWI8JdtlvHMyRvt/es0rdsygjk9YHfVR3FEWua9VVfsFMKTVVjCf/gH2V+7jqVlNP1uSMp2TfH7LUpfeWXkutO31VnxRX1ZIDhRaI="
        - secure: "PNJ2NZioKdt5jyBMDpKxtPCUY2MV+dou/V8JRyuoeh0vlBZ5ujrFSbwNOb4xyEjFGBLK/bqIL2jm6vBEbNnvL2TTk20ybVKQDl+QivMjSHajwcbr8mtmwpe3HVC+QC68PXS1wITOWO8GZnvkLn8SQoLSSEoR4Maj9z2HY+W7ZBs="
    - jdk: openjdk-ea
      env:
        - BASE_URL=s3://storage.yandexcloud.net/s3-tests
        - secure: "H35SN7WfvG52NIOmE7QzzWkSxGPSXijftejiUt1OwHMbr9jtp9NWk8SxFNabaKXpOW9xg9PnzyDOiORFxKWtqzzdrqcVZTHrXN652b0EA3YXr1QFM0HLGy1paiMVksYPDO73PVWeQvDaxthHzB+Ysff+QhN67vC7sbsRCOG7KXo="
        - secure: "jSJS2PbNVozYnWl4b7/1WOCby8JtvyuM3FE8ulF4jrxEFKAxn3hlSo+EgehZnk5C4/gMBuEljSE+W95NQzgKhEDk1gpHfCqYGjRjwCxsEXK+qRBUSopI0GFsQVAtSZc3nky+NNqDRs8UBMP+rNxAfysw5b+4hKK8M3fw3oTdwrg="
    - jdk: openjdk-ea
      env:
        - BASE_URL=s3://s3-tests.storage.yandexcloud.net/
        - secure: "H35SN7WfvG52NIOmE7QzzWkSxGPSXijftejiUt1OwHMbr9jtp9NWk8SxFNabaKXpOW9xg9PnzyDOiORFxKWtqzzdrqcVZTHrXN652b0EA3YXr1QFM0HLGy1paiMVksYPDO73PVWeQvDaxthHzB+Ysff+QhN67vC7sbsRCOG7KXo="
        - secure: "jSJS2PbNVozYnWl4b7/1WOCby8JtvyuM3FE8ulF4jrxEFKAxn3hlSo+EgehZnk5C4/gMBuEljSE+W95NQzgKhEDk1gpHfCqYGjRjwCxsEXK+qRBUSopI0GFsQVAtSZc3nky+NNqDRs8UBMP+rNxAfysw5b+4hKK8M3fw3oTdwrg="

    - jdk: oraclejdk11
      env:
        - BASE_URL=s3://s3-tests.s3-eu-west-1.amazonaws.com
        - secure: "UAZpxNjODj8kfIr70zWwVSRZtMKD/bXql8kLq5HQ+i5i+5COIzEBrs+4snj5ENmg6TuNNhOWI8JdtlvHMyRvt/es0rdsygjk9YHfVR3FEWua9VVfsFMKTVVjCf/gH2V+7jqVlNP1uSMp2TfH7LUpfeWXkutO31VnxRX1ZIDhRaI="
        - secure: "PNJ2NZioKdt5jyBMDpKxtPCUY2MV+dou/V8JRyuoeh0vlBZ5ujrFSbwNOb4xyEjFGBLK/bqIL2jm6vBEbNnvL2TTk20ybVKQDl+QivMjSHajwcbr8mtmwpe3HVC+QC68PXS1wITOWO8GZnvkLn8SQoLSSEoR4Maj9z2HY+W7ZBs="
    - jdk: oraclejdk11
      env:
        - BASE_URL=s3://s3.eu-central-1.amazonaws.com/s3-tests-2
        - secure: "UAZpxNjODj8kfIr70zWwVSRZtMKD/bXql8kLq5HQ+i5i+5COIzEBrs+4snj5ENmg6TuNNhOWI8JdtlvHMyRvt/es0rdsygjk9YHfVR3FEWua9VVfsFMKTVVjCf/gH2V+7jqVlNP1uSMp2TfH7LUpfeWXkutO31VnxRX1ZIDhRaI="
        - secure: "PNJ2NZioKdt5jyBMDpKxtPCUY2MV+dou/V8JRyuoeh0vlBZ5ujrFSbwNOb4xyEjFGBLK/bqIL2jm6vBEbNnvL2TTk20ybVKQDl+QivMjSHajwcbr8mtmwpe3HVC+QC68PXS1wITOWO8GZnvkLn8SQoLSSEoR4Maj9z2HY+W7ZBs="
    - jdk: oraclejdk11
      env:
        - BASE_URL=s3://s3.amazonaws.com/s3-tests-3
        - secure: "UAZpxNjODj8kfIr70zWwVSRZtMKD/bXql8kLq5HQ+i5i+5COIzEBrs+4snj5ENmg6TuNNhOWI8JdtlvHMyRvt/es0rdsygjk9YHfVR3FEWua9VVfsFMKTVVjCf/gH2V+7jqVlNP1uSMp2TfH7LUpfeWXkutO31VnxRX1ZIDhRaI="
        - secure: "PNJ2NZioKdt5jyBMDpKxtPCUY2MV+dou/V8JRyuoeh0vlBZ5ujrFSbwNOb4xyEjFGBLK/bqIL2jm6vBEbNnvL2TTk20ybVKQDl+QivMjSHajwcbr8mtmwpe3HVC+QC68PXS1wITOWO8GZnvkLn8SQoLSSEoR4Maj9z2HY+W7ZBs="
    - jdk: oraclejdk11
      env:
        - BASE_URL=s3://storage.yandexcloud.net/s3-tests
        - secure: "H35SN7WfvG52NIOmE7QzzWkSxGPSXijftejiUt1OwHMbr9jtp9NWk8SxFNabaKXpOW9xg9PnzyDOiORFxKWtqzzdrqcVZTHrXN652b0EA3YXr1QFM0HLGy1paiMVksYPDO73PVWeQvDaxthHzB+Ysff+QhN67vC7sbsRCOG7KXo="
        - secure: "jSJS2PbNVozYnWl4b7/1WOCby8JtvyuM3FE8ulF4jrxEFKAxn3hlSo+EgehZnk5C4/gMBuEljSE+W95NQzgKhEDk1gpHfCqYGjRjwCxsEXK+qRBUSopI0GFsQVAtSZc3nky+NNqDRs8UBMP+rNxAfysw5b+4hKK8M3fw3oTdwrg="
    - jdk: oraclejdk11
      env:
        - BASE_URL=s3://s3-tests.storage.yandexcloud.net/
        - secure: "H35SN7WfvG52NIOmE7QzzWkSxGPSXijftejiUt1OwHMbr9jtp9NWk8SxFNabaKXpOW9xg9PnzyDOiORFxKWtqzzdrqcVZTHrXN652b0EA3YXr1QFM0HLGy1paiMVksYPDO73PVWeQvDaxthHzB+Ysff+QhN67vC7sbsRCOG7KXo="
        - secure: "jSJS2PbNVozYnWl4b7/1WOCby8JtvyuM3FE8ulF4jrxEFKAxn3hlSo+EgehZnk5C4/gMBuEljSE+W95NQzgKhEDk1gpHfCqYGjRjwCxsEXK+qRBUSopI0GFsQVAtSZc3nky+NNqDRs8UBMP+rNxAfysw5b+4hKK8M3fw3oTdwrg="


  allow_failures:
    - jdk: openjdk-ea

after_success:
  - mvn -V -B -e jacoco:report
  - bash <(curl -s https://codecov.io/bash)
